// src/components/sections/about.tsx
import { motion } from 'motion/react';

export const AboutSection = () => {
  return (
    <div className="grid grid-col-1 sm:grid-cols-3 gap-4">
      <div className="flex flex-col col-span-2 col-start-1 row-start-2 sm:row-start-1">
        <motion.h2
          initial={{ y: 25, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="text-foreground text-3xl leading-loose font-medium col-span-2 row-start-1 font-display-2">
          Hi, I'm Asad! A full-stack developer based in Bandung, Indonesia 🇮🇩
        </motion.h2>
        <div className="h-8"></div>
        <motion.p
          className="text-foreground text-xl leading-relaxed col-span-2 row-start-2"
          initial={{ y: 25, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.5 }}>
          I'm an experienced full-stack with a proven background spanning over
          5+ years, coupled with valuable exposure to project and team
          management. My experience include building and maintaining web-app,
          server-side API, cross-platform mobile app, and browser extensions.
          I’ve built and maintained web apps, server-side APIs, cross-platform
          mobile apps, and browser extensions.
        </motion.p>
        <div className="h-4"></div>
        <motion.p
          className="text-foreground text-xl leading-relaxed col-span-2 row-start-2"
          initial={{ y: 25, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.75 }}>
          In addition, I’ve been actively learning DevOps to expand my skill set
          and am eager to gain hands-on experience in this area.
        </motion.p>
        <div className="h-4"></div>
        <motion.p
          className="text-foreground text-xl leading-relaxed col-span-2 row-start-2"
          initial={{ y: 25, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5, delay: 1 }}>
          Outside of work, I'm also active in local communities. I frequently
          attend local bookclub meetings where I share about my reading journey,
          and listen to the stories of others. I'm also a coordinator of a
          foreign language conversation club,{' '}
          <a
            href="https://www.instagram.com/soekabahasa"
            className="text-accent font-bold">
            Soekabahasa
          </a>
          , where I help to organize the club's events, activities and
          continuously reviewing and suggesting ideas to improve the club's
          experience.
        </motion.p>
        <div className="h-4"></div>
        <motion.p
          className="text-foreground text-xl leading-relaxed col-span-2 row-start-2"
          initial={{ y: 25, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.95 }}>
          In my spare time, you can find me reading books, writing, learning
          language, or running.
        </motion.p>
      </div>
      <motion.img
        initial={{ scale: 2, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.75, ease: 'circOut' }}
        src="/whats-this.png"
        className="rounded-full row-start-1 w-64 sm:w-80"
        width="auto"
      />
    </div>
  );
};

// src/routes/about/+page.svelte
<script lang="ts">
	import { fly, scale, fade } from 'svelte/transition';
</script>

<section class="grid grid-cols-3 gap-4 rounded-2xl border-4 border-black p-2 sm:p-6">
	<div class="col-span-2 flex flex-col space-y-4 sm:row-start-1">
		<h2
			in:fly={{ y: 25, opacity: 0, duration: 400 }}
			class="font-display bg-secondary-500 rounded-lg border-4 border-black p-4 text-3xl leading-relaxed font-bold text-black shadow-[4px_4px_0_0_black] sm:text-4xl"
		>
			Hi, I'm Asad! A full-stack developer based in Bandung, Indonesia 🇮🇩
		</h2>

		<p
			in:fly={{ y: 25, opacity: 0, duration: 400, delay: 200 }}
			class="rounded-md border-4 border-black bg-blue-100 p-4 text-xl leading-relaxed text-black shadow-[4px_4px_0_0_black]"
		>
			I'm an experienced full-stack with a proven background spanning over 5+ years, coupled with
			valuable exposure to project and team management. My experience includes building and
			maintaining web apps, server-side APIs, cross-platform mobile apps, and browser extensions.
		</p>

		<p
			in:fly={{ y: 25, opacity: 0, duration: 400, delay: 400 }}
			class="rounded-md border-4 border-black bg-green-100 p-4 text-xl leading-relaxed text-black shadow-[4px_4px_0_0_black]"
		>
			In addition, I’ve been actively learning DevOps to expand my skill set and am eager to gain
			hands-on experience in this area.
		</p>

		<p
			in:fly={{ y: 25, opacity: 0, duration: 400, delay: 600 }}
			class="rounded-md border-4 border-black bg-pink-100 p-4 text-xl leading-relaxed text-black shadow-[4px_4px_0_0_black]"
		>
			Outside of work, I'm also active in local communities. I frequently attend local book club
			meetings and coordinate{' '}
			<a href="https://www.instagram.com/soekabahasa" class="font-bold text-blue-600 underline">
				Soekabahasa
			</a>, a foreign language conversation club, where I help organize events and improve member
			experiences.
		</p>

		<p
			in:fly={{ y: 25, opacity: 0, duration: 400, delay: 800 }}
			class="rounded-md border-4 border-black bg-purple-100 p-4 text-xl leading-relaxed text-black shadow-[4px_4px_0_0_black]"
		>
			In my spare time, you can find me reading books, writing, learning languages, or running.
		</p>
	</div>

	<div class="flex items-start justify-center sm:items-center">
		<img
			src="/whats-this.png"
			alt="Illustration"
			class="w-64 rounded-full border-4 border-black shadow-[6px_6px_0_0_black] sm:w-80"
			in:scale={{ start: 2, duration: 500 }}
		/>
	</div>
</section>
